language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libboost-thread-dev 
      - libboost-system-dev
      - libboost-regex-dev
      - libboost-date-time-dev 
      - libboost-test-dev
      - google-mock
 
before_script:
  - "cd /usr/src/gmock && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ && sudo mv gtest/libg* /usr/local/lib/ ; cd -"

script: ./travis.sh 
