language: cpp
os:
  - linux
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
env:
  - GMOCK_VER=1.8.0 
  - GMOCK_VER=1.7.0 
  - GMOCK_PATH=/usr/src/gmock #1.6.0 from ubuntu trusty repo
matrix:
  include:
    - os: linux
      compiler: gcc
      env: GMOCK_VER=1.8.0 VALGRIND_TESTS=ON
    - os: osx
      compiler: clang
      env: GMOCK_VER=1.8.0 QT_DIR=/usr/local/Cellar/qt5/5.8.0_1
    - os: osx
      compiler: clang
      env: GMOCK_VER=1.7.0 QT_DIR=/usr/local/Cellar/qt5/5.8.0_1

addons:
  apt:
    packages:
      - libboost-thread-dev 
      - libboost-system-dev
      - libboost-regex-dev
      - libboost-date-time-dev 
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - google-mock
      - ninja-build
      - valgrind
      - qtbase5-dev

before_install:
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then brew update && brew install ninja qt5; fi

script: ./travis.sh 

# default notifications: https://docs.travis-ci.com/user/notifications#Notifications
